### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by nizamsp** [smooch/smooch-android#10]
Fatal Exception: java.lang.IncompatibleClassChangeError: Couldn't find com.google.gson.annotations.SerializedName.value
       at libcore.reflect.AnnotationAccess.toAnnotationInstance(AnnotationAccess.java:659)
       at libcore.reflect.AnnotationAccess.toAnnotationInstance(AnnotationAccess.java:641)
       at libcore.reflect.AnnotationAccess.getDeclaredAnnotation(AnnotationAccess.java:170)
       at java.lang.reflect.Field.getAnnotation(Field.java:242)
       at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getFieldName(Unknown Source)
       at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getFieldName(Unknown Source)
       at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(Unknown Source)
       at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(Unknown Source)
       at com.google.gson.Gson.getAdapter(Unknown Source)
       at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getFieldAdapter(Unknown Source)
       at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.access$100(Unknown Source)
       at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.(Unknown Source)
       at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(Unknown Source)
       at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(Unknown Source)
       at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(Unknown Source)
       at com.google.gson.Gson.getAdapter(Unknown Source)
       at com.google.gson.Gson.fromJson(Unknown Source)
       at com.google.gson.Gson.fromJson(Unknown Source)
       at com.google.gson.Gson.fromJson(Unknown Source)
       at com.google.gson.Gson.fromJson(Unknown Source)
       at io.smooch.core.facade.impl.a.a(Unknown Source)
       at io.smooch.core.facade.g.a(Unknown Source)
       at io.smooch.core.facade.impl.f.run(Unknown Source)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:145)
       at android.app.ActivityThread.main(ActivityThread.java:6145)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)

I am seeing this crash on Samsung SM-A500G on Android 5.0.2

Looks like the following link has some solution.
https://github.com/google/gson/issues/726

**Comment by jugarrit** [comment]
Please re-open with repro steps.
Thanks.
