### ISSUE TITLE
java.lang.NoClassDefFoundError: com.google.firebase.iid.FirebaseInstanceId

### ISSUE THREAD

**Issue by ArjunKP10p501** [smooch/smooch-android#100]
java.lang.NoClassDefFoundError: com.google.firebase.iid.FirebaseInstanceId
                                                                                 at io.smooch.core.service.SmoochService$36.a(Unknown Source)
                                                                                 at io.smooch.core.service.SmoochService$36.a(Unknown Source)
                                                                                 at io.smooch.core.b.f$1.a(Unknown Source)
                                                                                 at io.smooch.core.b.a.b$1$2.run(Unknown Source)
                                                                                 at android.os.Handler.handleCallback(Handler.java:800)
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:100)
                                                                                 at android.os.Looper.loop(Looper.java:194)
                                                                                 at android.app.ActivityThread.main(ActivityThread.java:5391)
                                                                                 at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                 at java.lang.reflect.Method.invoke(Method.java:525)
                                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:833)
                                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600)
                                                                                 at dalvik.system.NativeStart.main(Native Method)

**Comment by wmora** [comment]
if you are using google play services or firebase, note that Smooch uses version `11.0.4` and all libraries should have the same version. Refer to this [comment](https://github.com/smooch/smooch-android/issues/54#issuecomment-257305344) for an example on how to do that

**Comment by wmora** [comment]
Feel free to reopen if the issue persists
