### ISSUE TITLE
App crashes when receiving Smooch notification for the first time when the app is killed 

### ISSUE THREAD

**Issue by SamiKh94** [smooch/smooch-android#101]
Log: 
`java.lang.NullPointerException: Attempt to invoke virtual method 'void io.smooch.core.b.f.a(io.smooch.core.c.b, io.smooch.core.b.e)' on a null object reference
                                                                          at io.smooch.core.service.SmoochService.T(Unknown Source)
                                                                          at io.smooch.core.service.SmoochService.h(Unknown Source)
                                                                          at io.smooch.core.b$7.run(Unknown Source)
                                                                          at io.smooch.core.b.v(Unknown Source)
                                                                          at io.smooch.core.b.a(Unknown Source)
                                                                          at io.smooch.core.b.q(Unknown Source)
                                                                          at io.smooch.core.FcmService.triggerSmoochNotification(Unknown Source)`

**Comment by wmora** [comment]
Which version of the SDK are you using?

**Comment by SamiKh94** [comment]
i am using v5.2.0

**Comment by wmora** [comment]
Fixed in [v5.2.1](https://github.com/smooch/smooch-android/releases/tag/5.2.1). Thanks for reporting!
