### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by nizamsp** [smooch/smooch-android#11]
Fatal Exception: android.app.RemoteServiceException: Bad notification posted from package com.myapp.android: Couldn't expand RemoteViews for: StatusBarNotification(pkg=com.myapp.android user=UserHandle{0} id=1 tag=Smooch score=10: Notification(pri=1 contentView=com.myapp.android/0x1090064 vibrate=default sound=default defaults=0xffffffff flags=0x11 kind=[null]))
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1488)
       at android.os.Handler.dispatchMessage(Handler.java:110)
       at android.os.Looper.loop(Looper.java:193)
       at android.app.ActivityThread.main(ActivityThread.java:5292)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:824)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:640)
       at dalvik.system.NativeStart.main(NativeStart.java)

**Comment by jugarrit** [comment]
Please re-open the issue with steps to reproduce the problem.
Thanks.
