### ISSUE TITLE
Crash with ConcurrentModificationException on SDK 5.12.5

### ISSUE THREAD

**Issue by islamassi** [smooch/smooch-android#117]
**Bug Report**
App crashes:

`Caused by java.util.ConcurrentModificationException
       at java.util.LinkedList$ListItr.checkForComodification(LinkedList.java:967)
       at java.util.LinkedList$ListItr.next(LinkedList.java:888)
       at io.smooch.core.c.y(Unknown Source)
       at io.smooch.core.c.a(Unknown Source)
       at io.smooch.core.c.m(Unknown Source)
       at io.smooch.core.Conversation.markAllAsRead(Unknown Source)
       at io.smooch.ui.fragment.ConversationFragment.onResume(Unknown Source)
       at android.support.v4.app.Fragment.performResume(Fragment.java:2390)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1474)
       at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1759)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1827)
       at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3244)
       at android.support.v4.app.FragmentManagerImpl.dispatchResume(FragmentManager.java:3212)
       at android.support.v4.app.FragmentController.dispatchResume(FragmentController.java:217)
       at android.support.v4.app.FragmentActivity.onResumeFragments(FragmentActivity.java:509)
       at android.support.v4.app.FragmentActivity.onPostResume(FragmentActivity.java:498)
       at android.support.v7.app.AppCompatActivity.onPostResume(AppCompatActivity.java:171)
       at android.app.Activity.performResume(Activity.java:7082)
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3765)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3828)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2991)
       at android.app.ActivityThread.-wrap14(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1635)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6692)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)`

`Fatal Exception: java.lang.RuntimeException: Unable to resume activity {yamsafer.yamsafer.me/yamsafer.yamsafer.me.Activitys.ChatActivity}: java.util.ConcurrentModificationException
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3788)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3828)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2991)
       at android.app.ActivityThread.-wrap14(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1635)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6692)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)`

`private synchronized void y() {
        if (this.j.size() > 0 && !this.x()) {
            ArrayList var1 = new ArrayList();
            Iterator var2 = this.j.iterator();

            while(var2.hasNext()) {
                Runnable var3 = (Runnable)var2.next();
                if (this.x()) {
                    break;
                }

                var3.run();
                var1.add(var3);
            }

            this.j.removeAll(var1);
        }

    }`
More details : `http://crashes.to/s/f033c9e2e9e`

 **Please tell us about your environment:**
- SDK version 5.12.5
This crash appeares also on SDK 5.12.2

**Comment by wmora** [comment]
Thanks for reporting, we'll look into it

**Comment by islamassi** [comment]
Thank you very much. I will upgrade to 5.13.0 and update you about the issue if fixed.

**Comment by islamassi** [comment]
@wmora 
It seems that one of the two crashes were solved but the other one is not.

Current version 5.13.2:
Solved crash:    http://crashes.to/s/1394ccd8ac0
unsolved:           http://crashes.to/s/ae17f70c1f0

I will upgrade to the latest version and will update you on the issue.

**Comment by islamassi** [comment]
@wmora 
The issue persists on version `5.14.1`
Fabric: http://crashes.to/s/5a357507651
