### ISSUE TITLE
ClassNotFoundException: NotificationCompat support v7 

### ISSUE THREAD

**Issue by Scythe14** [smooch/smooch-android#118]
Hi Guys, 

I hope everyone is doing ok. I just found a new issue in the library.

I think changing NotificationCompat can solve my crash issue. The NotificationCompat version is deprecated and can be replace by the supported one by replacing 
`import android.support.v7.app.NotificationCompat` by ` import android.support.v4.app.NotificationCompat`. 

I have reproduced it by sending a clientside message (from smooch library) to the serverside chat (Gorgias), kill the app or put it in background, answer (serverside: Gorgias) the message (while the app is not running in foreground), launching the app and then the crash happened while initializing Smooch I guess.

Btw, I am using the 5.12.5 version of the library.

Thank you for helping ! :) 

 ```
java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v7/app/NotificationCompat$Builder;
        at io.smooch.ui.NotificationController$1.postVisit(Unknown Source)
        at io.smooch.ui.utils.AsyncImageLoader$a.a(Unknown Source)
        at io.smooch.ui.utils.AsyncImageLoader$a.onPostExecute(Unknown Source)
        at android.os.AsyncTask.finish(AsyncTask.java:632)
        at android.os.AsyncTask.access$600(AsyncTask.java:177)
        at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:645)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5272)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:909)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:704)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.v7.app.NotificationCompat$Builder" on path: DexPathList[[zip file "/data/app/com.frichti.android-1/base.apk"],nativeLibraryDirectories=[/data/app/com.frichti.android-1/lib/arm, /vendor/lib, /system/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
        at io.smooch.ui.NotificationController$1.postVisit(Unknown Source) 
        at io.smooch.ui.utils.AsyncImageLoader$a.a(Unknown Source) 
        at io.smooch.ui.utils.AsyncImageLoader$a.onPostExecute(Unknown Source) 
        at android.os.AsyncTask.finish(AsyncTask.java:632) 
        at android.os.AsyncTask.access$600(AsyncTask.java:177) 
        at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:645) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:135) 
        at android.app.ActivityThread.main(ActivityThread.java:5272) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:372) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:909) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:704) 
    	Suppressed: java.lang.ClassNotFoundException: android.support.v7.app.NotificationCompat$Builder
        at java.lang.Class.classForName(Native Method)
        at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
        at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
        		... 14 more
     Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available
```

**Comment by wmora** [comment]
Hello,

The SDK uses `android.support.v4.app.NotificationCompat`. Are you trying to use the `v7` version in your app?

**Comment by Scythe14** [comment]
Hi @wmora and thank you for your quick answer. I am using 
 ```android.support.v4.app.NotificationCompat``` in the app, so I don't really understand what could cause the crash. Do you have an idea ?

**Comment by wmora** [comment]
Could you provide a sample app with the same dependencies you are using in your app that reproduces the issue?

**Comment by Scythe14** [comment]
Hi @wmora I managed to fix the crash by downgrade the version of the android support from 27.1.1 to 26.1.0. Well that's not the best way to do it, but at least, it is working haha. Thx for your time

**Comment by amit6061** [comment]
import androidx.core.app.NotificationCompat;
I have used then error occurred 
java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v7/app/NotificationCompat$Builder;
