### ISSUE TITLE
NullPointerException in MessageViewBuilder.build: invoke 'double java.lang.Double.doubleValue()' on a null object

### ISSUE THREAD

**Issue by islamassi** [smooch/smooch-android#120]
**Bug Report**

App crashes with the following exception:

`Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'double java.lang.Double.doubleValue()' on a null object reference
       at io.smooch.ui.builder.MessageViewBuilder.build(Unknown Source)
       at io.smooch.ui.adapter.MessageListAdapter.setReplies(Unknown Source)
       at io.smooch.ui.adapter.MessageListAdapter.setReplies(Unknown Source)
       at io.smooch.ui.adapter.MessageListAdapter.setReplies(Unknown Source)
       at android.support.v7.widget.RecyclerView$Adapter.onCreateViewHolder(RecyclerView.java:6673)
       at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6714)
       at android.support.v7.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5647)
       at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5913)
       at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5752)
       at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5748)
       at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2232)
       at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1559)
       at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1519)
       at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:614)
       at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3812)
       at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3529)
       at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:4082)
       at android.view.View.layout(View.java:17838)
       at android.view.ViewGroup.layout(ViewGroup.java:5754)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1982)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1826)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1735)
       at android.view.View.layout(View.java:17838)
       at android.view.ViewGroup.layout(ViewGroup.java:5754)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:383)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:321)
       at android.view.View.layout(View.java:17838)
       at android.view.ViewGroup.layout(ViewGroup.java:5754)
       at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1189)
       at android.view.View.layout(View.java:17838)
       at android.view.ViewGroup.layout(ViewGroup.java:5754)
       at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1189)
       at android.view.View.layout(View.java:17838)
       at android.view.ViewGroup.layout(ViewGroup.java:5754)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:383)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:321)
       at android.view.View.layout(View.java:17838)
       at android.view.ViewGroup.layout(ViewGroup.java:5754)
       at android.support.v7.widget.ActionBarOverlayLayout.onLayout(ActionBarOverlayLayout.java:443)
       at android.view.View.layout(View.java:17838)
       at android.view.ViewGroup.layout(ViewGroup.java:5754)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:383)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:321)
       at android.view.View.layout(View.java:17838)
       at android.view.ViewGroup.layout(ViewGroup.java:5754)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1982)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1826)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1735)
       at android.view.View.layout(View.java:17838)
       at android.view.ViewGroup.layout(ViewGroup.java:5754)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:383)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:321)
       at com.android.internal.policy.DecorView.onLayout(DecorView.java:751)
       at android.view.View.layout(View.java:17838)
       at android.view.ViewGroup.layout(ViewGroup.java:5754)
       at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2711)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2384)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1462)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6965)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:907)
       at android.view.Choreographer.doCallbacks(Choreographer.java:709)
       at android.view.Choreographer.doFrame(Choreographer.java:644)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:893)
       at android.os.Handler.handleCallback(Handler.java:836)
       at android.os.Handler.dispatchMessage(Handler.java:103)
       at android.os.Looper.loop(Looper.java:203)
       at android.app.ActivityThread.main(ActivityThread.java:6251)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1063)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:924)`

Fabric: 
http://crashes.to/s/9094e3ac4e2

- SDK version: 5.12.5

**Comment by ImDroidGuy** [comment]
Same issue in version io.smooch:ui:5.12.5,

**Comment by wmora** [comment]
have you been able to reproduce?

**Comment by wmora** [comment]
We identified the issue and will be fixed in the next release

**Comment by islamassi** [comment]
Thank you very much.

**Comment by islamassi** [comment]
Thank you very much.
