### ISSUE TITLE
Proguard issue after updating Firebase Cloud Messaging SDK

### ISSUE THREAD

**Issue by raylee4204** [smooch/smooch-android#136]
**What is the current behavior?**
Proguard throws errors after updating Firebase Cloud Messaging SDK to 18.0.0

 **Please provide the steps to reproduce and, if possible, a minimal demo of the problem**. Ideally a sample project

Use following Firebase Messaging SDK version by: 

implementation 'com.google.firebase:firebase-messaging:18.0.0'

Proguard throws warnings:

Warning: io.smooch.core.FcmInstanceIDListenerService: can't find superclass or interface com.google.firebase.iid.FirebaseInstanceIdService
Warning: io.smooch.core.FcmInstanceIDListenerService: can't find referenced class com.google.firebase.iid.FirebaseInstanceIdService
Warning: io.smooch.core.FcmInstanceIDListenerService: can't find referenced class com.google.firebase.iid.FirebaseInstanceIdService

 **What is the expected behavior?**
No exceptions should be thrown

 **Please tell us about your environment:**
- SDK version: 5.17.4 - 5.19.0
- OS version 9.0.0

**Comment by raylee4204** [comment]
@wmora any update on this?

**Comment by kanblack** [comment]
me too, runtime crash everytime init smooch

java.lang.NullPointerException: throw with null exception
        at io.smooch.core.d.e.b(Unknown Source:3)
        at io.smooch.core.service.SmoochService.a(Unknown Source:2)
        at io.smooch.core.service.SmoochService.a(Unknown Source:0)
        at io.smooch.core.service.U.a(Unknown Source:44)
        at io.smooch.core.service.U.a(Unknown Source:2)
        at io.smooch.core.b.q.a(Unknown Source:25)
        at io.smooch.core.b.g.a(Unknown Source:29)
        at io.smooch.core.b.a$h.run(Unknown Source:12)
        at android.os.Handler.handleCallback(Handler.java:792)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:176)
        at android.app.ActivityThread.main(ActivityThread.java:6701)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:246)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:783)

**Comment by wmora** [comment]
no updates yet, will look into it and let you know

**Comment by wmora** [comment]
firebase 18.0.0 introduces a couple of breaking changes to our SDK. We'll work on an update and release a new version. Will update this issue once released

**Comment by wmora** [comment]
Fixed in [v6.0.0](https://github.com/smooch/smooch-android/releases/tag/6.0.0)
