### ISSUE TITLE
NPE when clicking on "Take Photo" (4.0.2)

### ISSUE THREAD

**Issue by skolarianer** [smooch/smooch-android#41]
```
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.contains(java.lang.CharSequence)' on a null object reference
  at io.smooch.ui.fragment.ConversationFragment.dispatchTakePhotoIntent(Unknown Source)
  at io.smooch.ui.fragment.ConversationFragment.access$2300(Unknown Source)
  at io.smooch.ui.fragment.ConversationFragment$6.onClick(Unknown Source)
  at com.android.internal.app.AlertController$AlertParams$3.onItemClick(AlertController.java:1082)
  at android.widget.AdapterView.performItemClick(AdapterView.java:305)
  at android.widget.AbsListView.performItemClick(AbsListView.java:1148)
  at android.widget.AbsListView$PerformClick.run(AbsListView.java:3059)
  at android.widget.AbsListView$3.run(AbsListView.java:3866)
  at android.os.Handler.handleCallback(Handler.java:739)
  at android.os.Handler.dispatchMessage(Handler.java:95)
  at android.os.Looper.loop(Looper.java:135)
  at android.app.ActivityThread.main(ActivityThread.java:5294)
  at java.lang.reflect.Method.invoke(Native Method)
  at java.lang.reflect.Method.invoke(Method.java:372)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
```

**Comment by jugarrit** [comment]
Should be fixed in the new version 4.0.4.
Please re-open if it reproduces!
