### ISSUE TITLE
Crash due to ConcurrentModificationException in Smooch

### ISSUE THREAD

**Issue by ajarl** [smooch/smooch-android#46]
I implemented Smooch in my Android app, and it has been working fine so far. Just now, however, I sent a message and the app crashed with this stack trace:

```
E/AndroidRuntime: FATAL EXCEPTION: main
  Process: (my process name), PID: 32130
  java.util.ConcurrentModificationException
      at java.util.ArrayList$ArrayListIterator.next(ArrayList.java:573)
      at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.write(CollectionTypeAdapterFactory.java:96)
      at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.write(CollectionTypeAdapterFactory.java:61)
      at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:68)
      at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.write(ReflectiveTypeAdapterFactory.java:112)
      at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.write(ReflectiveTypeAdapterFactory.java:239)
      at com.google.gson.Gson.toJson(Gson.java:661)
      at com.google.gson.Gson.toJson(Gson.java:640)
      at com.google.gson.Gson.toJson(Gson.java:595)
      at com.google.gson.Gson.toJson(Gson.java:575)
      at io.smooch.core.b.a.c.a(Unknown Source)
      at io.smooch.core.b.c.a(Unknown Source)
      at io.smooch.core.service.SmoochService.a(Unknown Source)
      at io.smooch.core.service.SmoochService.b(Unknown Source)
      at io.smooch.core.service.SmoochService$10$1.a(Unknown Source)
      at io.smooch.core.service.SmoochService$10$1.a(Unknown Source)
      at io.smooch.core.b.f$7.a(Unknown Source)
      at io.smooch.core.b.a.b$1$2.run(Unknown Source)
      at android.os.Handler.handleCallback(Handler.java:739)
(snip)
```

This only happened once so far, so can't really say what caused it. I'm using 4.0.2. Just noticed 4.0.4 is out, going to try with that version now.

**Comment by jugarrit** [comment]
Since it's really hard for me to figure out what went wrong, the best I can do is make an attempt at fixing this. I'll push something in the next release

**Comment by jugarrit** [comment]
Please try 4.0.5 and see if the problem persists.
Re-open if it does.
Thanks
