### ISSUE TITLE
Crashe

### ISSUE THREAD

**Issue by nizamsp** [smooch/smooch-android#52]
Around 298 users got the following Crash.
Device distribution.
samsung43%
LENOVO11%
Micromax7%
Other…39%

OS version happening:
5 36%
6 33%
4 30%
Other…1%

16% of the crash happened in "App In Focus"
Please let me know if you need anymore details to reproduce the crash.

Fatal Exception: java.lang.IllegalStateException: Fragment a{3f95ef31} not attached to Activity
       at android.support.v4.app.Fragment.getResources(SourceFile:636)
       at android.support.v4.app.Fragment.getString(SourceFile:658)
       at io.smooch.ui.fragment.ConversationFragment$12.run(Unknown Source)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5292)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)

Is there a stable version of smooch? I see some crashes on every release.

**Comment by wmora** [comment]
[v4.2.1](https://github.com/smooch/smooch-android/releases/tag/4.2.1) has been released with the fix

**Comment by almaziskhakov** [comment]
Hi.
I use v4.2.1, but I have this crash too

Fatal Exception: java.lang.IllegalStateException: Fragment a{259b1af0} not attached to Activity
       at android.support.v4.app.Fragment.getResources(SourceFile:646)
       at android.support.v4.app.Fragment.getString(SourceFile:668)
       at io.smooch.ui.fragment.ConversationFragment$15.run(Unknown Source)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5253)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:949)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:744)

**Comment by wmora** [comment]
hmmm, this seems to happen at a different place. We'll look into it, thanks for reporting

**Comment by Quabynah** [comment]
Same problem here....but there is a solution to that if you use an older version of the smooch ui

**Comment by wmora** [comment]
Fixed in [v4.5.1](https://github.com/smooch/smooch-android/releases/tag/4.5.1)
