### ISSUE TITLE
App crashes when using latest smooch version (4.0.5) with Google play service 9.6.1

### ISSUE THREAD

**Issue by viettanbkdn** [smooch/smooch-android#54]
Smooch is using Firebase v9.4.0, which is not compatible with Google play service v9.6.1, so the app will be crashed when init Smooch:

`java.lang.NoSuchMethodError: No static method zzb(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object; in class Lcom/google/android/gms/common/internal/zzab; or its super classes (declaration of 'com.google.android.gms.common.internal.zzab' appears in /data/app/com.***.***/base.apk)
                                                       at com.google.firebase.provider.FirebaseInitProvider.zza(Unknown Source)
                                                       at com.google.firebase.provider.FirebaseInitProvider.attachInfo(Unknown Source)
                                                       at android.app.ActivityThread.installProvider(ActivityThread.java:6762)
                                                       at android.app.ActivityThread.installContentProviders(ActivityThread.java:6357)
                                                       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6297)
                                                       at android.app.ActivityThread.access$1800(ActivityThread.java:221)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1860)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:158)
                                                       at android.app.ActivityThread.main(ActivityThread.java:7224)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)`

**Comment by wmora** [comment]
Hey there,

You can update the Firebase version in your project to be in sync with your Play Services version. Include the Firebase dependency in your project's `build.gradle` file and set both to the same version, it will override the version provided by Smooch. Ex:

    dependencies {
        compile 'com.google.android.gms:play-services:9.6.1'
        compile 'com.google.firebase:firebase-core:9.6.1'
        compile 'com.google.firebase:firebase-messaging:9.6.1'
        // other dependencies
    }

**Comment by wmora** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[Android] App crashes when using latest smooch version (4.0.5) with Google play service 9.6.1](https://trello.com/c/F6m99ZLi/4822-android-app-crashes-when-using-latest-smooch-version-4-0-5-with-google-play-service-9-6-1)

**Comment by viettanbkdn** [comment]
Fixed it, thanks, you can close this issue @wmora
