### ISSUE TITLE
Unexpected char 0x915 at 0 in User-Agent value: कोड हब/1.0 (motorola XT1034; Android 4.4.2)

### ISSUE THREAD

**Issue by itsPR** [smooch/smooch-android#56]
Fatal Exception: java.lang.IllegalArgumentException: Unexpected char 0x915 at 0 in User-Agent value: कोड हब/1.0 (motorola XT1034; Android 4.4.2)
       at okhttp3.r$a.d(SourceFile:320)
       at okhttp3.r$a.c(SourceFile:300)
       at okhttp3.z$a.a(SourceFile:163)
       at io.smooch.core.b.a.b.a(Unknown Source)
       at io.smooch.core.b.a.b.a(Unknown Source)
       at io.smooch.core.b.a.a(Unknown Source)
       at io.smooch.core.b.a.a(Unknown Source)
       at io.smooch.core.b.f.a(Unknown Source)
       at io.smooch.core.service.SmoochService.i(Unknown Source)
       at io.smooch.core.p.a(Unknown Source)
       at io.smooch.core.p$1.onServiceConnected(Unknown Source)
       at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1110)
       at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1127)
       at android.os.Handler.handleCallback(Handler.java:733)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:136)
       at android.app.ActivityThread.main(ActivityThread.java:5102)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
       at dalvik.system.NativeStart.main(NativeStart.java)

**Comment by itsPR** [comment]
issue related to non-ascii characters in user agent

**Comment by ancloid** [comment]
The same with Cyrillic:
Crash: Unexpected char 0x412 at 0 in User-Agent value: Вебка/1.65 (samsung SM-G800H; Android 5.1.1)

**Comment by wmora** [comment]
[v4.1.1](https://github.com/smooch/smooch-android/releases/tag/4.1.1) has been released fixing this issue. Thanks for reporting
