### ISSUE TITLE
NPE prepareImagePreview

### ISSUE THREAD

**Issue by p-hells** [smooch/smooch-android#58]
Hi,

Can you help me with this one?

java.lang.NullPointerException
   at io.smooch.ui.widget.MessageView.prepareImagePreview(Unknown Source)
   at io.smooch.ui.widget.MessageView$1.onLoadingComplete(Unknown Source)
   at com.nostra13.universalimageloader.core.DisplayBitmapTask.run(DisplayBitmapTask.java:72)
   at android.os.Handler.handleCallback(Handler.java:605)
   at android.os.Handler.dispatchMessage(Handler.java:92)
   at android.os.Looper.loop(Looper.java:154)
   at android.app.ActivityThread.main(ActivityThread.java:4624)
   at java.lang.reflect.Method.invokeNative(Native Method)
   at java.lang.reflect.Method.invoke(Method.java:511)
   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:809)
   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:576)
   at dalvik.system.NativeStart.main(Native Method)

**Comment by wmora** [comment]
Hi, is this error happening repeatedly? Are you able to reproduce it?

**Comment by p-hells** [comment]
Yes, it's happen each time I open ConversationActivity (in a case I send image before). Tested on several devices. Seems related to my project settings, but I can't find any limitations in your docs (except the FileProvider, but I didn't use it in my project)

**Comment by wmora** [comment]
Ok, could you maybe post some sample code or project where the issue can be reproduced? Or maybe be more specific about your project settings?

**Comment by p-hells** [comment]
Sample with similar settings works correctly. Thank you for the help. I'll try to figure out what exacly affects on this behavior in my project

**Comment by wmora** [comment]
Ok, great!

**Comment by p-hells** [comment]
This issue occurs because of com.nostra13.universalimageloader lib that I uses in my projects. My own ImageLoader config contains diskCacheSize option. Setting it calls conflict with your lib.

`ImageLoaderConfiguration config = new ImageLoaderConfiguration.Builder(applicationContext)
...
.diskCacheSize(DISK_CACHE_SIZE)
...
.build();
ImageLoader.getInstance().init(config);`

`public static final int DISK_CACHE_SIZE = 100 * 1024 * 1024;`
