### ISSUE TITLE
SecurityException after taking a photo

### ISSUE THREAD

**Issue by p-hells** [smooch/smooch-android#60]
Hi,

I get crash after taking a photo in the ConversationActivity (reproducible each time). I dont't use FileProvider in my project.

java.lang.SecurityException: Permission Denial: opening provider android.support.v4.content.FileProvider from ProcessRecord{41e439d0 9547:com.android.camera/10007} (pid=9547, uid=10007) that is not exported from uid 10063
    at android.os.Parcel.readException(Parcel.java:1327)
    at android.os.Parcel.readException(Parcel.java:1281)
    at android.app.ActivityManagerProxy.getContentProvider(ActivityManagerNative.java:2201)
    at android.app.ActivityThread.acquireProvider(ActivityThread.java:4185)
    at android.app.ContextImpl$ApplicationContentResolver.acquireProvider(ContextImpl.java:1636)
    at android.content.ContentResolver.acquireProvider(ContentResolver.java:939)
    at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:559)
    at android.content.ContentResolver.openOutputStream(ContentResolver.java:432)
    at android.content.ContentResolver.openOutputStream(ContentResolver.java:408)
    at com.android.camera.Camera.doAttach(Camera.java:1713)
    at com.android.camera.Camera.onReviewDoneClicked(Camera.java:1690)
    at java.lang.reflect.Method.invokeNative(Native Method) 
    at java.lang.reflect.Method.invoke(Method.java:511) 
    at android.view.View$1.onClick(View.java:3045) 
    at android.view.View.performClick(View.java:3517) 
    at android.view.View$PerformClick.run(View.java:14155) 
    at android.os.Handler.handleCallback(Handler.java:605) 
    at android.os.Handler.dispatchMessage(Handler.java:92) 
    at android.os.Looper.loop(Looper.java:154) 
    at android.app.ActivityThread.main(ActivityThread.java:4624) 
    at java.lang.reflect.Method.invokeNative(Native Method) 
    at java.lang.reflect.Method.invoke(Method.java:511) 
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:809) 
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:576) 
    at dalvik.system.NativeStart.main(Native Method) 

Thanks in advance. 
Also a small question: can I disable the "Take Photo" feature at all?

**Comment by jugarrit** [comment]
Hey there!

We'll be sure to take a look at the problem as soon as we have a chance.
As for disabling the feature, unfortunately that's not possible.

Thanks for reporting.

**Comment by p-hells** [comment]
Thanks,

Btw it's reproducable (each time) at 4.0.4 (fly iq450). Work without error at 6.0.1 (galaxy s6)

**Comment by almaziskhakov** [comment]
Have same problem, in android 6 and higher it works normally with requesting permission, but in lower it crashes with same error

**Comment by DrKein** [comment]
Have same problem, any update?

**Comment by wmora** [comment]
We have already filed the issue internally and will provide a fix as soon as we have a chance.

Thanks for your patience!

**Comment by wmora** [comment]
This was fixed in version 4.2.0: https://github.com/smooch/smooch-android/releases/tag/4.2.0
