### ISSUE TITLE
java.lang.NoSuchMethodError: No static method zzb(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object; in class Lcom/google/android/gms/common/internal/zzab;

### ISSUE THREAD

**Issue by AndreiD** [smooch/smooch-android#62]
Hello,

If I add the smooch libraries:

```
  compile 'io.smooch:core:latest.release'
  compile 'io.smooch:ui:latest.release'
```

I get a crash at the launch of the application

```
java.lang.NoSuchMethodError: No static method zzb(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object; in class Lcom/google/android/gms/common/internal/zzab; or its super classes (declaration of 'com.google.android.gms.common.internal.zzab' appears in /data/data/com.androidadvance.hive.debug/files/instant-run/dex/slice-com.google.android.gms-play-services-base-10.0.1_d5a82033bd2c0a0a7c623128b58290f1f5910b1a-classes.dex)
                                                                                   at com.google.firebase.provider.FirebaseInitProvider.zza(Unknown Source)
                                                                                   at com.google.firebase.provider.FirebaseInitProvider.attachInfo(Unknown Source)
                                                                                   at android.app.ActivityThread.installProvider(ActivityThread.java:5811)
                                                                                   at android.app.ActivityThread.installContentProviders(ActivityThread.java:5403)
                                                                                   at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5342)
                                                                                   at android.app.ActivityThread.-wrap2(ActivityThread.java)
                                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1528)
                                                                                   at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                   at android.os.Looper.loop(Looper.java:154)
                                                                                   at android.app.ActivityThread.main(ActivityThread.java:6077)
                                                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
                                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)

```

Without the smooch libs, the application runs just fine.
Here's my gradle config

```

apply plugin: 'com.android.application'
apply plugin: 'com.neenbedankt.android-apt'
apply plugin: 'me.tatarka.retrolambda'

apply from: '../config/quality.gradle'



android {
  compileSdkVersion 25
  buildToolsVersion "24.0.0"

  defaultConfig {
    applicationId "com.androidadvance.hive"
    minSdkVersion 15
    targetSdkVersion 25
    versionCode 1
    versionName "1.0"
    testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"

    manifestPlaceholders = [manifestApplicationId: "${applicationId}",
                            onesignal_app_id: "19181xxxxxxxxxxxxxxxxxx",
                            onesignal_google_project_number: "70377xxxxxxxxxxxxxx"]
  }
  buildTypes {
    release {
      minifyEnabled false
      shrinkResources false
      proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
      signingConfig signingConfigs.config
    }

    debug {
      applicationIdSuffix ".debug"
      debuggable true
    }
  }

  compileOptions {
    sourceCompatibility JavaVersion.VERSION_1_8
    targetCompatibility JavaVersion.VERSION_1_8
  }

  packagingOptions {
    exclude 'META-INF/DEPENDENCIES'
    exclude 'LICENSE.txt'
    exclude 'META-INF/LICENSE'
    exclude 'META-INF/LICENSE.txt'
    exclude 'META-INF/NOTICE'
    exclude 'LICENSE.txt'
  }

  lintOptions {
    warning 'InvalidPackage'
    abortOnError false
    lintConfig file("${project.rootDir}/config/quality/lint/lint.xml")
  }

  configurations.all {
    resolutionStrategy {
      force 'com.android.support:support-annotations:23.0.1'
    }
  }
}


dependencies {

  compile fileTree(dir: 'libs', include: ['*.jar'])

  //----- Support Libs
  compile "com.android.support:appcompat-v7:25.0.1"
  compile "com.android.support:design:25.0.1"
  compile "com.android.support:recyclerview-v7:25.0.1"
  compile "com.android.support:cardview-v7:25.0.1"

  //----- Dagger
  compile "com.google.dagger:dagger:2.0.2"
  apt "com.google.dagger:dagger-compiler:2.0.2"
  provided 'org.glassfish:javax.annotation:10.0-b28' //Required by Dagger2

  //----- Rx
  compile "io.reactivex:rxandroid:1.1.0"
  compile "io.reactivex:rxjava:1.1.0"

  //----- Retrofit
  compile 'com.squareup.retrofit2:retrofit:2.0.0-beta3'  //2.1.0
  compile "com.squareup.retrofit2:converter-gson:2.0.0-beta3"
  compile "com.squareup.retrofit2:adapter-rxjava:2.0.0-beta3"
  compile 'com.squareup.okhttp3:logging-interceptor:3.0.1'

  //---- DbFlow
  apt "com.github.Raizlabs.DBFlow:dbflow-processor:3.0.0-beta1"
  compile "com.github.Raizlabs.DBFlow:dbflow-core:3.0.0-beta1"
  compile "com.github.Raizlabs.DBFlow:dbflow:3.0.0-beta1"

  //----- Butterknife
  compile "com.jakewharton:butterknife:7.0.1"

  //----- Eventbuss
  compile "de.greenrobot:eventbus:2.4.0" //3.0.0

  //----- Logging
  compile 'com.github.zhaokaiqiang.klog:library:1.5.0'

  //----- Picasso
  compile "com.squareup.picasso:picasso:2.5.2"

  //------ Circular ImageView
  compile "com.mikhaellopez:circularimageview:2.1.1"

  //----- Easy Permission Management
  compile "com.karumi:dexter:2.2.0"

  //----- Annotations
  compile "org.glassfish:javax.annotation:10.0-b28"

  //----- One Signal & GCM
  compile 'com.onesignal:OneSignal:2.+@aar'  // compile 'com.onesignal:OneSignal:3.+@aar'
  compile 'com.google.android.gms:play-services-gcm:+'
  compile "com.google.android.gms:play-services-location:+"

  compile 'pl.charmas.android:android-reactive-location:0.10@aar' //0.10

  compile 'io.smooch:core:latest.release'
  compile 'io.smooch:ui:latest.release'

}

```

## Any ideas why this is happening ? 😢

**Comment by wmora** [comment]
Hello! The latest version of Smooch includes Firebase 9.4.0 and it seems like you are using a newer version of Play Services in your project. Both libraries need to have the same version number, refer to https://github.com/smooch/smooch-android/issues/54 for a fix and let us know if it works

**Comment by AndreiD** [comment]
Yes, it's working with 9.4.0. 
also I had to update the okhttp3 library... for some kind of reason that I didn't had time to investigate.

compile 'com.squareup.okhttp3:okhttp:3.5.0'
compile 'com.squareup.okhttp3:logging-interceptor:3.5.0'

**Comment by AndreiD** [comment]
Thank you for your very fast help
