### ISSUE TITLE
Non english App title is crashing smooch sdk

### ISSUE THREAD

**Issue by nizamsp** [smooch/smooch-android#63]
If the user's phone's default language is hindi and the app initialization causing a fatal crash. Following is the traceback.
```


                                                                                  java.lang.IllegalArgumentException: Unexpected char 0x91a at 0 in User-Agent value: चलती /4.3.4-debug (Huawei Nexus 6P; Android 7.1.1)
 at okhttp3.Headers$Builder.checkNameAndValue(Headers.java:320)
                                                                                      at okhttp3.Headers$Builder.set(Headers.java:300)
                                                                                      at okhttp3.Request$Builder.header(Request.java:163)
                                                                                      at io.smooch.core.b.a.b.a(Unknown Source)
                                                                                      at io.smooch.core.b.a.b.a(Unknown Source)
                                                                                      at io.smooch.core.b.a.a(Unknown Source)
                                                                                      at io.smooch.core.b.a.a(Unknown Source)
                                                                                      at io.smooch.core.b.f.a(Unknown Source)
                                                                                      at io.smooch.core.service.SmoochService.i(Unknown Source)
                                                                                      at io.smooch.core.b.a(Unknown Source)
                                                                                      at io.smooch.core.b$1.onServiceConnected(Unknown Source)
                                                                                      at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1453)
                                                                                      at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1481)
                                                                                      at android.os.Handler.handleCallback(Handler.java:751)
                                                                                      at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                      at android.os.Looper.loop(Looper.java:154)
                                                                                      at android.app.ActivityThread.main(ActivityThread.java:6119)
                                                                                      at java.lang.reflect.Method.invoke(Native Method)
                                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

**Comment by wmora** [comment]
Hi, which version of the SDK are you using? Version 4.1.1 should have this issue fixed

**Comment by nizamsp** [comment]
Cool. I just upgraded it and its working. Thanks for the prompt reply.
