### ISSUE TITLE
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/iid/InstanceID

### ISSUE THREAD

**Issue by nizamsp** [smooch/smooch-android#7]
I am getting this crash on the first launch after install.
Am I missing anything?

FATAL EXCEPTION: IntentService[GcmRegIntentService]
                                                                            Process: com.xxxxxxxxxx.android, PID: 20519
                                                                            java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/iid/InstanceID;
                                                                                at io.smooch.core.GcmRegistrationIntentService.onHandleIntent(Unknown Source)
                                                                                at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
                                                                                at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                at android.os.Looper.loop(Looper.java:135)
                                                                                at android.os.HandlerThread.run(HandlerThread.java:61)
                                                                             Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.iid.InstanceID" on path: DexPathList[[zip file "/data/app/com.xxxxxxx.android-1/base.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
                                                                                at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                                at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
                                                                                at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
                                                                                at io.smooch.core.GcmRegistrationIntentService.onHandleIntent(Unknown Source) 
                                                                                at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65) 
                                                                                at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                at android.os.Looper.loop(Looper.java:135) 
                                                                                at android.os.HandlerThread.run(HandlerThread.java:61) 
                                                                            	Suppressed: java.lang.ClassNotFoundException: com.google.android.gms.iid.InstanceID
                                                                                at java.lang.Class.classForName(Native Method)
                                                                                at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
                                                                                at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
                                                                                at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
                                                                                		... 6 more
                                                                             Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack availabl

**Comment by jugarrit** [comment]
This issue can be fixed by including a valid version of `com.google.android.gms:play-services-gcm`.

**Comment by lakshmianusha1** [comment]
What is the valid version of com.google.android.gms:play-services-gcm.I am facing the same problem from many days.Thanks in advance

**Comment by lakshmianusha1** [comment]
What is the valid version of com.google.android.gms:play-services-gcm? I am facing the same problem from many days.please suggest to do better

**Comment by lakshmianusha1** [comment]
I am facing same issue.Please suggest me to do better

**Comment by wmora** [comment]
the latest version of the SDK (4.6.1) uses play services 10.0.1
