### ISSUE TITLE
App crashes with play-service 10.2.4

### ISSUE THREAD

**Issue by DrKein** [smooch/smooch-android#74]
**Smooch has no problem with play-service 10.0.1**

But if we use  10.2.4....

when call ConversationActivity,  logcat printing various errors something like 
> java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/internal/zzzv$zza;

**AND when finishing ConversationActivity, app crashes with** 
> java.lang.AbstractMethodError: abstract method "java.lang.String com.google.android.gms.common.internal.zzf.zzez()"
                                         at com.google.android.gms.common.internal.zzf.zzxy(Unknown Source)
                                         at com.google.android.gms.common.internal.zzf.zza(Unknown Source)
                                         at com.google.android.gms.common.internal.zzf.disconnect(Unknown Source)
                                         at com.google.android.gms.internal.zzaru.disconnect(Unknown Source)
                                         at com.google.android.gms.internal.zzaav.zzwu(Unknown Source)
                                         at com.google.android.gms.internal.zzaas.begin(Unknown Source)
                                         at com.google.android.gms.internal.zzaav.zzh(Unknown Source)
                                         at com.google.android.gms.internal.zzaar.disconnect(Unknown Source)
                                         at com.google.android.gms.internal.zzaav.disconnect(Unknown Source)
                                         at com.google.android.gms.internal.zzaat.disconnect(Unknown Source)
                                         at io.smooch.ui.fragment.ConversationFragment.onStop(Unknown Source)
                                         at android.support.v4.app.Fragment.performStop(Fragment.java:2376)
                                         at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1360)
                                         at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1523)
                                         at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1585)
                                         at android.support.v4.app.FragmentManagerImpl.dispatchStop(FragmentManager.java:2855)
                                         at android.support.v4.app.FragmentController.dispatchStop(FragmentController.java:245)
                                         at android.support.v4.app.FragmentActivity.onStop(FragmentActivity.java:627)
                                         at android.support.v7.app.AppCompatActivity.onStop(AppCompatActivity.java:187)
                                         at io.smooch.ui.ConversationActivity.onStop(Unknown Source)
                                         at android.app.Instrumentation.callActivityOnStop(Instrumentation.java:1289)
                                         at android.app.Activity.performStop(Activity.java:6857)
                                         at android.app.ActivityThread.performStopActivityInner(ActivityThread.java:3864)
                                         at android.app.ActivityThread.handleStopActivity(ActivityThread.java:3916)
                                         at android.app.ActivityThread.-wrap25(ActivityThread.java)
                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1512)
                                         at android.os.Handler.dispatchMessage(Handler.java:102)
                                         at android.os.Looper.loop(Looper.java:154)
                                         at android.app.ActivityThread.main(ActivityThread.java:6121)
                                         at java.lang.reflect.Method.invoke(Native Method)
                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)

**Comment by skolarianer** [comment]
The versions of all Google Play Services libraries must be in sync. According to http://www.methodscount.com/?lib=io.smooch%3Aui%3A4.5.1 smooch uses version 10.0.1 of these libs:
* com.google.android.gms:play-services-base
* com.google.android.gms:play-services-basement
* com.google.android.gms:play-services-location
* com.google.android.gms:play-services-tasks
+ a bunch of firebase libs.

**Comment by jugarrit** [comment]
As @skolarianer pointed out, you'd need all versions of the libraries to be in sync. If you require that version one possible solution is to override the versions as explained here: https://github.com/smooch/smooch-android/issues/54#issuecomment-257305344

Hope that helps!

**Comment by sandro-csimas** [comment]
I solved by using these dependencies:
