### ISSUE TITLE
User.getCurrentUser() throws RuntimeException

### ISSUE THREAD

**Issue by justincpollard** [smooch/smooch-android#79]
I have a singleton in my app that monitors changes in the current user. This includes an event fired immediately upon app start. Upon the event firing, the singleton attempts to update Smooch's `User` properties. For example:

`User.getCurrentUser().setFirstName(firstName);`

Unfortunately, this ends up causing an exception in Smooch:

```
java.lang.RuntimeException: Can't create handler inside thread that has not called Looper.prepare()
                                                                         at android.os.Handler.<init>(Handler.java:200)
                                                                         at android.os.Handler.<init>(Handler.java:114)
                                                                         at io.smooch.core.User.<init>(Unknown Source)
                                                                         at io.smooch.core.User.getCurrentUser(Unknown Source)
                                                                         at com.myapp.chat.ChatManager.setUserFirstName(ChatManager.java:55)
                                                                         at com.myapp.chat.ChatManager.lambda$new$548(ChatManager.java:32)
                                                                         at com.myapp.chat.ChatManager$$Lambda$1.call(Unknown Source)
                                                                         at rx.internal.util.ActionObserver.onNext(ActionObserver.java:39)
                                                                         at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onNext(OnSubscribeDoOnEach.java:96)
                                                                         at rx.internal.operators.OperatorDistinctUntilChanged$1.onNext(OperatorDistinctUntilChanged.java:102)
                                                                         at rx.internal.operators.NotificationLite.accept(NotificationLite.java:128)
                                                                         at rx.subjects.SubjectSubscriptionManager$SubjectObserver.emitNext(SubjectSubscriptionManager.java:253)
                                                                         at rx.subjects.BehaviorSubject.onNext(BehaviorSubject.java:160)
                                                                         at com.myapp.auth.Session.setUserModel(Session.java:111)
                                                                         at com.myapp.auth.Session.onError(Session.java:237)
                                                                         at com.myapp.auth.Session.access$lambda$0(Session.java:0)
                                                                         at com.myapp.auth.Session$$Lambda$7.call(Unknown Source)
                                                                         at rx.internal.util.ActionSubscriber.onError(ActionSubscriber.java:44)
                                                                         at rx.observers.SafeSubscriber._onError(SafeSubscriber.java:153)
                                                                         at rx.observers.SafeSubscriber.onError(SafeSubscriber.java:115)
                                                                         at rx.internal.operators.OperatorSubscribeOn$SubscribeOnSubscriber.onError(OperatorSubscribeOn.java:80)
                                                                         at retrofit2.adapter.rxjava.BodyOnSubscribe$BodySubscriber.onNext(BodyOnSubscribe.java:53)
                                                                         at retrofit2.adapter.rxjava.BodyOnSubscribe$BodySubscriber.onNext(BodyOnSubscribe.java:36)
                                                                         at retrofit2.adapter.rxjava.CallArbiter.deliverResponse(CallArbiter.java:115)
                                                                         at retrofit2.adapter.rxjava.CallArbiter.emitResponse(CallArbiter.java:97)
                                                                         at retrofit2.adapter.rxjava.CallExecuteOnSubscribe.call(CallExecuteOnSubscribe.java:46)
                                                                         at retrofit2.adapter.rxjava.CallExecuteOnSubscribe.call(CallExecuteOnSubscribe.java:24)
                                                                         at retrofit2.adapter.rxjava.BodyOnSubscribe.call(BodyOnSubscribe.java:33)
                                                                         at retrofit2.adapter.rxjava.BodyOnSubscribe.call(BodyOnSubscribe.java:25)
                                                                         at rx.Observable.unsafeSubscribe(Observable.java:10256)
                                                                         at rx.internal.operators.OperatorSubscribeOn$SubscribeOnSubscriber.call(OperatorSubscribeOn.java:100)
                                                                         at rx.internal.schedulers.CachedThreadScheduler$EventLoopWorker$1.call(CachedThreadScheduler.java:230)
                                                                         at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
                                                                         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
                                                                         at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                         at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
                                                                         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                                         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                         at java.lang.Thread.run(Thread.java:761)
```

**Comment by wmora** [comment]
instead of executing this immediately upon app start, listen to [`onInitializationStatusChanged`](https://docs.smooch.io/api/android/io/smooch/core/Conversation.Delegate.html#onInitializationStatusChanged-io.smooch.core.InitializationStatus-) instead and update the first name when the status changes to [`Success`](https://docs.smooch.io/api/android/io/smooch/core/InitializationStatus.html#Success). 

If you are already doing it this way, could you please upload a sample project reproducing the issue?

**Comment by justincpollard** [comment]
@wmora thanks for the response! I'm not clear on where to listen for status changed events. It looks like `Smooch.getInitializationStatus()` pulls in the current status. I also see `Smooch.getConversation().setDelegate()` where the Delegate is the one you linked to above. Is that the correct method to use?

**Comment by justincpollard** [comment]
@wmora ok, so I tried a couple things and still see the problem. I've confirmed (using the debugger) that `onInitializationStatusChanged` is called with a value of `Success` before I try to access the Smooch User. I'll try to get you an example project illustrating the issue.

**Comment by justincpollard** [comment]
What looks like is happening is that I'm calling `User.getCurrentUser().setEmail()` (for example) or a non-UI thread (I'm using RxJava 1 and am calling this method on an RxIoScheduler). Is this not allowed? Here's a repo that illustrates the issue:

https://github.com/justincpollard/SmoochTest

**Comment by wmora** [comment]
@justincpollard thanks for the sample code! There was indeed an issue when first calling `User.getCurrentUser()` from a non-UI thread. Version [4.6.1](https://github.com/smooch/smooch-android/releases/tag/4.6.1) fixes the issue

**Comment by justincpollard** [comment]
Thank you for fixing @wmora!
