### ISSUE TITLE
java.lang.AbstractMethodError: abstract method "java.lang.String com.google.android.gms.common.internal.zzf.zzez()"

### ISSUE THREAD

**Issue by malmstein** [smooch/smooch-android#86]
Our app is crashing after closing the `ConversationActivity`.

```
06-09 12:01:36.612 21116-21116/? E/AndroidRuntime: FATAL EXCEPTION: main
Process: net.helpscout.android, PID: 21116
java.lang.AbstractMethodError: abstract method "java.lang.String com.google.android.gms.common.internal.zzf.zzez()"
at com.google.android.gms.common.internal.zzf.zzxy(Unknown Source)
at com.google.android.gms.common.internal.zzf.zza(Unknown Source)
at com.google.android.gms.common.internal.zzf.disconnect(Unknown Source)
at com.google.android.gms.internal.zzaru.disconnect(Unknown Source)
at com.google.android.gms.internal.zzaav.zzwu(Unknown Source)
at com.google.android.gms.internal.zzaas.begin(Unknown Source)
at com.google.android.gms.internal.zzaav.zzh(Unknown Source)
at com.google.android.gms.internal.zzaar.disconnect(Unknown Source)
at com.google.android.gms.internal.zzaav.disconnect(Unknown Source)
at com.google.android.gms.internal.zzaat.disconnect(Unknown Source)
at io.smooch.ui.c.a.onStop(Unknown Source)
at android.support.v4.app.Fragment.performStop(Unknown Source)
 at android.support.v4.app.u.a(Unknown Source)
at android.support.v4.app.u.d(Unknown Source)
at android.support.v4.app.u.a(Unknown Source)
at android.support.v4.app.u.p(Unknown Source)
at android.support.v4.app.r.k(Unknown Source)
at android.support.v4.app.p.onStop(Unknown Source)
at android.support.v7.app.e.onStop(Unknown Source)
at io.smooch.ui.ConversationActivity.onStop(Unknown Source)
at android.app.Instrumentation.callActivityOnStop(Instrumentation.java:1289)
at android.app.Activity.performStop(Activity.java:6854)
at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4160)
at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4221)
at android.app.ActivityThread.-wrap6(ActivityThread.java)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1538)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:154)
at android.app.ActivityThread.main(ActivityThread.java:6119)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

We are using proguard, and I'm using the configuration from https://github.com/smooch/smooch-android/issues/13

```
# Smooch ProGuard rules.
# https://github.com/smooch/smooch-android

-dontwarn okio.**
-keep class com.google.gson.** { *; }
-keepattributes Signature
-keepattributes *Annotation*
-keepclassmembers enum * { *; }
```

**Comment by malmstein** [comment]
I was too quick to post this one, if anyone has the same issue simply follow https://github.com/smooch/smooch-android/issues/74
