### ISSUE TITLE
NoClassDefFoundError: okhttp3.MediaType

### ISSUE THREAD

**Issue by ArjunKP10p501** [smooch/smooch-android#91]
java.lang.NoClassDefFoundError: okhttp3.MediaType
            at io.smooch.core.b.a.b.<clinit>(Unknown Source)
            at io.smooch.core.b.b.a(Unknown Source)
            at io.smooch.core.b.b.a(Unknown Source)
            at io.smooch.core.service.SmoochService.<init>(Unknown Source)
            at java.lang.Class.newInstanceImpl(Native Method)
            at java.lang.Class.newInstance(Class.java:1319)
            at android.app.ActivityThread.handleCreateService(ActivityThread.java:2692)
            at android.app.ActivityThread.access$1600(ActivityThread.java:165)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1455)
            at android.os.Handler.dispatchMessage(Handler.java:107)
            at android.os.Looper.loop(Looper.java:194)
            at android.app.ActivityThread.main(ActivityThread.java:5391)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:525)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:833)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600)
            at dalvik.system.NativeStart.main(Native Method)

**Comment by hishamdubizzle** [comment]
I am facing the same issue with io.smooch:core:4.7.2
please help

**Comment by wmora** [comment]
When is this exception being thrown? When the app is initialized? If so, it may be due to your app needing to [enable multidex](https://developer.android.com/studio/build/multidex.html#mdex-gradle). Otherwise, you may try to explicitly include okhttp as a dependency under your app's dependencies:

```
compile 'com.squareup.okhttp3:okhttp:3.4.1'
```

**Comment by hishamdubizzle** [comment]
thanks for reply
for me, issue fixed by enabling multi dex

**Comment by wmora** [comment]
great, @ArjunKP10p501 feel free to reopen if this doesn't solve it for you
