### ISSUE TITLE
ConcurrentModificationException

### ISSUE THREAD

**Issue by comgra** [smooch/smooch-android#98]
when get more than one message, for example get 3 messages at same time, it will crash with this exception, log as: (not happen always)
java.util.ConcurrentModificationException
                                                                            at java.util.ArrayList$ArrayListIterator.next(ArrayList.java:573)
                                                                            at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.write(CollectionTypeAdapterFactory.java:95)
                                                                            at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.write(CollectionTypeAdapterFactory.java:60)
                                                                            at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:68)
                                                                            at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.write(ReflectiveTypeAdapterFactory.java:113)
                                                                            at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.write(ReflectiveTypeAdapterFactory.java:240)
                                                                            at com.google.gson.Gson.toJson(Gson.java:605)
                                                                            at com.google.gson.Gson.toJson(Gson.java:584)
                                                                            at com.google.gson.Gson.toJson(Gson.java:539)
                                                                            at com.google.gson.Gson.toJson(Gson.java:519)
                                                                            at io.smooch.core.b.a.c.a(Unknown Source)
                                                                            at io.smooch.core.b.c.a(Unknown Source)
                                                                            at io.smooch.core.service.SmoochService.q(Unknown Source)
                                                                            at io.smooch.core.b$13.run(Unknown Source)
                                                                            at io.smooch.core.b.v(Unknown Source)
                                                                            at io.smooch.core.b.a(Unknown Source)
                                                                            at io.smooch.core.b.m(Unknown Source)
                                                                            at io.smooch.core.Conversation.markAllAsRead(Unknown Source)
                                                                            at io.smooch.ui.fragment.ConversationFragment.onMessagesReceived(Unknown Source)
                                                                            at io.smooch.ui.ConversationActivity.onMessagesReceived(Unknown Source)
                                                                            at io.smooch.core.Conversation.f(Unknown Source)
                                                                            at io.smooch.core.Conversation.b(Unknown Source)
                                                                            at io.smooch.core.Conversation.b(Unknown Source)
                                                                            at io.smooch.core.Conversation$1.a(Unknown Source)
                                                                            at io.smooch.core.service.SmoochService$17.run(Unknown Source)
                                                                            at android.os.Handler.handleCallback(Handler.java:742)
                                                                            at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                            at android.os.Looper.loop(Looper.java:154)
                                                                            at android.app.ActivityThread.main(ActivityThread.java:5529)
                                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739)
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:629)

can you help with this? thanks

**Comment by jugarrit** [comment]
Thanks for providing a situation that we could potentially use to reproduce.
We will investigate and let you know when we have updates.

**Comment by comgra** [comment]
@jugarrit thanks

**Comment by BugFreeSoftware** [comment]
java.util.ConcurrentModificationException
    at java.util.ArrayList$Itr.next(ArrayList.java:831)
    at io.smooch.core.Conversation.f(Unknown Source)
    at io.smooch.core.Conversation.b(Unknown Source)
    at io.smooch.core.Conversation.b(Unknown Source)
    at io.smooch.core.Conversation$1.a(Unknown Source)
    at io.smooch.core.service.SmoochService$17.run(Unknown Source)
    at android.os.Handler.handleCallback(Handler.java:751)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:154)
    at android.app.ActivityThread.main(ActivityThread.java:6776)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)

**Comment by BugFreeSoftware** [comment]
I also got the one posted at the top but it stopped doing that after I removed markAllAsRead from onMessagesReceived. Using 5.0.1. Not impressed.

**Comment by jugarrit** [comment]
> it stopped doing that after I removed markAllAsRead from onMessagesReceived
Thanks, hopefully we can use that to help reproduce the issue.

**Comment by BugFreeSoftware** [comment]
Hopefully. The other one is still there, though...
It's a showstopper for us.
I also wasted a f*cking amount of time figuring out why the login callback never returns.
Turned out it never gets called because of the login caching.
Most time wasted because documentation is rudimentary to say the least.

**Comment by comgra** [comment]
@BugFreeSoftware hi, i tried remove markAllAsRead in onMessagesReceived, but also get this: 
java.util.ConcurrentModificationException
                                                                                at java.util.ArrayList$ArrayListIterator.next(ArrayList.java:573)
                                                                                at io.smooch.core.Conversation.f(Unknown Source)
                                                                                at io.smooch.core.Conversation.b(Unknown Source)
                                                                                at io.smooch.core.Conversation.b(Unknown Source)
                                                                                at io.smooch.core.Conversation$1.a(Unknown Source)
                                                                                at io.smooch.core.service.SmoochService$17.run(Unknown Source)
                                                                                at android.os.Handler.handleCallback(Handler.java:742)
                                                                                at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                at android.os.Looper.loop(Looper.java:154)
                                                                                at android.app.ActivityThread.main(ActivityThread.java:5529)
                                                                                at java.lang.reflect.Method.invoke(Native Method)
                                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739)
                                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:629)

**Comment by comgra** [comment]
@jugarrit hi, as it happens in f(), and happens to me when get more than one message at one time, i read your code in f():

```
    private void f() {
        LinkedList var1 = new LinkedList();
        Iterator var2 = this.e.b().iterator();

        while(var2.hasNext()) {
            l var3 = (l)var2.next();
            Message var4 = new Message(new l(var3));
            if(!this.c.contains(var4)) {
                var1.addFirst(var4);
            }
        }
......
```
here: Iterator var2 = this.e.b().iterator();
please consider this situation, three messages will be sent to client, two come early and when these two are in iterator(this.e.b() size is 2 now),  the third come(this.e.b() size changes to 3), so the exception happens unfortunately.
Is this possible?

**Comment by jugarrit** [comment]
Thanks for looking into the issue @comgra, it's a big help.
We have finally managed to reproduce the crash on our end and we will be fixing the problem in the next release.

**Comment by BugFreeSoftware** [comment]
Make sure to add a synchronize statements around all accesses to arrays like this that are multi-threaded.

**Comment by wmora** [comment]
[v5.0.2](https://github.com/smooch/smooch-android/releases/tag/5.0.2) fixes this issue, let us know if it happens again

**Comment by BugFreeSoftware** [comment]
Thank you for the short turn-around. Much appreciated. :-)

**Comment by comgra** [comment]
thank you! save my week!

**Comment by adrianrodriguez88** [comment]
Sorry but it keeps happening in version 5.9.1 always the first time I try to open the ConversationActivity, Maybe it's not the same scenario where it happens but it's the same exception. @wmora

E/AndroidRuntime: FATAL EXCEPTION: main
Process: mx.adrian.android.test, PID: 23874
java.lang.RuntimeException: Unable to resume activity {mx.adrian.android.test/io.smooch.ui.ConversationActivity}: java.util.ConcurrentModificationException
at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3314)
at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3345)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2659)
at android.app.ActivityThread.-wrap11(ActivityThread.java)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1488)
at android.os.Handler.dispatchMessage(Handler.java:111)
at android.os.Looper.loop(Looper.java:207)
at android.app.ActivityThread.main(ActivityThread.java:5728)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)
Caused by: java.util.ConcurrentModificationException
at java.util.LinkedList$LinkIterator.next(LinkedList.java:124)
at io.smooch.core.b.y(Unknown Source)
at io.smooch.core.b.a(Unknown Source)
at io.smooch.core.b.m(Unknown Source)
at io.smooch.core.Conversation.markAllAsRead(Unknown Source)
at io.smooch.ui.fragment.ConversationFragment.onResume(Unknown Source)
at android.support.v4.app.Fragment.performResume(Fragment.java:2401)
at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1465)
at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1740)
at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1809)
at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3217)
at android.support.v4.app.FragmentManagerImpl.dispatchResume(FragmentManager.java:3181)
at android.support.v4.app.FragmentController.dispatchResume(FragmentController.java:214)
at android.support.v4.app.FragmentActivity.onResumeFragments(FragmentActivity.java:470)
at android.support.v4.app.FragmentActivity.onPostResume(FragmentActivity.java:459)
at android.support.v7.app.AppCompatActivity.onPostResume(AppCompatActivity.java:171)
at android.app.Activity.performResume(Activity.java:6408)
at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3299)
at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3345) 
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2659) 
at android.app.ActivityThread.-wrap11(ActivityThread.java) 
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1488) 
at android.os.Handler.dispatchMessage(Handler.java:111) 
at android.os.Looper.loop(Looper.java:207) 
at android.app.ActivityThread.main(ActivityThread.java:5728) 
at java.lang.reflect.Method.invoke(Native Method) 
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789) 
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)

**Comment by BugFreeSoftware** [comment]
Hi William,

I moved on to another project in the mean time.
Too busy to fire up old repos atm. Sorry.

Eric.
